---
#- name: Create monitor network
#  docker_network:
#    name: portainer_agent_network
#    driver: overlay
#    attachable: yes

- name: Deploy monitor agent
  community.docker.docker_compose:
    project_name: portainer_agent
    definition:
      version: '3'
      services:
        portainer-agent:
          image: portainer/agent
          ports:
            - "9001:9001"
          environment:
            AGENT_CLUSTER_ADDR: tasks.portainer_agent
            AGENT_SECRET: "{{ portaineragent_shared_secret | default('', true) }}"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
